// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twwbdpwkmksuttqyblvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3d2JkcHdrbWtzdXR0cXlibHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjQzMjEsImV4cCI6MjA3MDgwMDMyMX0.ZLTK7WZe7HECXjtUQZ7Ls8MYCp_omNXcYti5YWRpJ7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});